# Generated by Django 5.2.7 on 2025-10-08 06:26

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Notaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('liste', models.TextField(null=True)),
                ('image', models.ImageField(upload_to=main_app.models.path_article_to)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.typearticle')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to=main_app.models.path_to)),
                ('chambre', models.SmallIntegerField()),
                ('salle_de_bain', models.SmallIntegerField()),
                ('surface', models.SmallIntegerField()),
                ('prix', models.IntegerField()),
                ('localisation', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('atout', models.TextField()),
                ('type_de_vente', models.CharField(choices=[('Acheter', 'Acheter'), ('Louer', 'Louer')], max_length=15)),
                ('notaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.notaire')),
                ('type_de_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.typebien')),
            ],
        ),
    ]
